CREATE TABLE APP.AUTH_NAME
(
USER_NAME varchar(255) NOT NULL,
U_PASS varchar(255),
PRIMARY KEY (USER_NAME)
);

CREATE TABLE APP.ACCOUNTS
(
USER_NAME varchar(255) NOT NULL,
ACCOUNT_STATE varchar(255),
BANK_NAME varchar(255),
PRIMARY KEY (USER_NAME),
CONSTRAINT FK_ACCOUNTS FOREIGN KEY (USER_NAME) REFERENCES APP.AUTH_NAME(USER_NAME)
);